### ISSUE TITLE
Can't logout when using session-rethinkdb

### ISSUE THREAD

**Issue by fasiha** [staygrimm/passwordless-rethinkdbstore#4]
Starting with the [simple-mail](https://github.com/florianheinemann/passwordless/tree/master/examples/simple-mail) example app that comes with Passwordless, I'm readily able to incorporate passwordless-rethinkdbstore. Everything works: hooray!

But when I add [session-rethinkdb](https://github.com/armenfilipetyan/express-session-rethinkdb) to my app (to replace the in-memory session store), I lose the ability to log out. I know this is probably not passwordless-rethinkdbstore's fault but I wanted to make absolutely sure before going to bug the session-rethinkdb people, since passwordless-rethinkdbstore is my only use-case for session-rethinkdb.

Here's how I initialize passwordless-rethinkdbstore:
```js
passwordless.init(new RethinkDBStore({host: '127.0.0.1', port: 28015, db: 'test'}));
```
And here's how I initialize express-session and session-rethinkdb:
```js
app.use(expressSession({
  secret : '42',
  resave : true,
  saveUninitialized : false,
  store : new RDBStore(
      {
        connectOptions : {db : 'test', host : 'localhost', port : 28015},
        table : 'sessionTest',
        sessionTimeout : 30*86400000,
        flushInterval : 60000
      })
}));
```
Am I doing something wrong here? I'd prefer to use RethinkDB for sessions, since that's what I'm using for passwordless (and my app).

**Comment by staygrimm** [comment]
I wrote this module 8 months ago and found that RethinkDB was way too slow at that point in time so I ended up using Redis for my Passwordless project.  I have not used RethinkDB since so I'm not really familiar with it but I can take a look at this tomorrow.

**Comment by PatrickKennedy** [comment]
I can confirm it's happening. I'm investigating myself, but initially, it is properly disposing of the document in the pwdless. Now to wrap my head around how the sessions actually work...

**Comment by PatrickKennedy** [comment]
This has been pulled into [session-rethinkdb](https://github.com/llambda/session-rethinkdb) v1.0.6 and there's a pull request for [express-session-rethinkdb](https://github.com/armenfilipetyan/express-session-rethinkdb) for v0.1.3. please update to those versions to resolve.

**Comment by staygrimm** [comment]
Awesome, thanks @PatrickKennedy!

**Comment by fasiha** [comment]
@PatrickKennedy FTW 😂!
